if(EXISTS "C:/Users/Khalid/Documents/PlatformIO/Projects/SensorNode-AVR/build_tests/run_tests[1]_tests.cmake")
  include("C:/Users/Khalid/Documents/PlatformIO/Projects/SensorNode-AVR/build_tests/run_tests[1]_tests.cmake")
else()
  add_test(run_tests_NOT_BUILT run_tests_NOT_BUILT)
endif()
